### ISSUE TITLE
Will not work for local spark master

### ISSUE THREAD

**Issue by javadba** [dportabella/spark-examples#2]
You are using "provided" which is fine for external spark processes but if master were "local[*]" or any other local then the spark libraries will be missing at runtime.

**Comment by dportabella** [comment]
I thought so first, and I created two configurations, one for local and one for spark-submit:
https://github.com/dportabella/spark-examples/tree/3b982a0c4aa16f7be887192d4a7de9ad2f9540e6

however, I noticed that it runs ok locally, even when defining `provided` dependencies, and so I removed the two different configurations. although i don't understand why it runs ok.
try it yourself: it works ok running locally, without external spark-submit:
`$ sbt -Dspark.master=local[2] "runMain org.apache.spark.examples.SparkPi 1000"`

**Comment by javadba** [comment]
Huh. The reason I brought it up is that we are experiencing runtime
libraries missing when doing the same approach with 'provided'.

2016-07-26 11:44 GMT-07:00 David Portabella notifications@github.com:

**Comment by dportabella** [comment]
any idea of why it is working in this case?
i don't understand myself how it is possible that it works locally with the provided dependencies.

**Comment by javadba** [comment]
I'll look down the road - sorry I gotta fix my project asap (where it
follows the rules - i.e. does *not *work..)

2016-07-26 12:13 GMT-07:00 David Portabella notifications@github.com:

**Comment by dportabella** [comment]
closing for now.
